site: ibnuuby
title: Hi, i'am Ibnu
description: >-
  Cyber Security Enthusiast <br> /home/kali/
lang: en-US
repo: https://github.com/ibnuuby/ibnuuby.github.io # site repo [optional]
data-theme: dark # default theme "dark" | "light"
#discus-identifier: mairacanal # replace with your disqus shortname

author:
  name: Ibnu Ubaeydillah
  picture: assets/images/profile.jpg
  username: ibnuuby
  github: ibnuuby
  email: me@ibnuby.com

# Font Settings
googlewebfonts: family=Play:wght@400;700&family=Source+Code+Pro:ital,wght@0,200;0,300;0,400;0,600;0,700;0,900;1,300;1,400;1,500;1,600;1,700;1,900

# URL settings
# url: "http://localhost:4000"
permalink: pretty

# local
# url: "http://localhost:4000" # 
# baseurl: "" # 


markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge


exclude:
  - .jekyll-cache
  - .obsidian
  - Gemfile
  - Gemfile.lock
  
compress_html:
  clippings: all
  comments: ["<!-- ", " -->"]

sass:
  sass_dir: _sass
  style: compressed

plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-relative-links

collections:
  pages:
    output: true
    permalink: /:name
  posts:
    output: true
    permalink: /:year/:month/:day/:slug
  
defaults:
  -
    scope:
      path: ""
    values:
      layout: "default"
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: "page"
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"

relative_links:
  enabled:     true
  collections: false


